apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: sandbox-transparent-capture.pratiks.io
spec:
  policyName: sandbox-transparent-capture.pratiks.io
  matchResources:
    namespaceSelector:
      matchLabels:
        sandbox.pratiks.io/enabled: "true"