apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicy
metadata:
  name: sandbox-dns-pod-mutation.pratiks.io
spec:
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  paramKind:
    apiVersion: v1
    kind: ConfigMap
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >-
          [
            JSONPatch{op: "add", path: "/spec/dnsPolicy", value: "None"},
            JSONPatch{
              op: "add",
              path: "/spec/dnsConfig",
              value: Object.spec.dnsConfig{
                nameservers: [string(params.data["sandboxDnsIP"])],
                searches: [request.namespace + ".svc." + string(params.data["clusterDomain"]), "svc." + string(params.data["clusterDomain"]), string(params.data["clusterDomain"])],
                options: [Object.spec.dnsConfig.options{name: "ndots", value: "5"}]
              }
            }
          ]
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >-
          Object{
            spec: Object.spec{
              volumes: [
                Object.spec.volumes{
                  name: "sandbox-ca-trust",
                  configMap: Object.spec.volumes.configMap{
                    name: "sandbox-ca-trust",
                  }
                }
              ],
              containers: object.spec.containers.map(container,
                Object.spec.containers{
                  name: container.name,
                  env: [Object.spec.containers.env{name: "NODE_EXTRA_CA_CERTS", value: "/var/run/sandbox-ca/ca.crt"}],
                  volumeMounts: [Object.spec.containers.volumeMounts{name: "sandbox-ca-trust", mountPath: "/var/run/sandbox-ca", readOnly: true}]
                }
              )
            }
          }
