apiVersion: v1
kind: ConfigMap
metadata:
  name: sandbox-dns-corefile
  namespace: sandbox-system-ns-1
  labels:
    app.kubernetes.io/name: sandbox-dns
    app.kubernetes.io/part-of: outbound-api-sandbox
data:
  Corefile: |
    cluster.local:53 {
        errors
        cache 30
        forward . 10.96.0.10
    }

    in-addr.arpa:53 {
        errors
        cache 30
        forward . 10.96.0.10
    }

    ip6.arpa:53 {
        errors
        cache 30
        forward . 10.96.0.10
    }

    .:53 {
        errors
        health :8080
        ready :8181
        prometheus :9153
        log
        cache 30
        forward . 10.96.0.10
        reload
    }
