apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFOzCCAyOgAwIBAgIUB50JZTE6EoCNlAHM+tQNiXgRqo8wDQYJKoZIhvcNAQEL
    BQAwNDEYMBYGA1UEAwwPU2FuZGJveCBSb290IENBMRgwFgYDVQQKDA9QcmF0aWtz
    IFNhbmRib3gwHhcNMjYwOTIzMTYyNzM4WhcNMzYwOTIwMTYyNzM4WjA0MRgwFgYD
    VQQDDA9TYW5kYm94IFJvb3QgQ0ExGDAWBgNVBAoMD1ByYXRpa3MgU2FuZGJveDCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAN7f8YSycTl9u1f9ki6RG2WM
    hSOj8rPM/AmVEvVFUP5rybkoXsV34Uevci978DSj/kHtY1bhw3RtbJMDTUJWpqYw
    oeZ2QK7os5cZYBdMi1vXnBc+gyeaOd6e+p3Ae3DIKpy+Z6RjSZwB+VzSvy3eO+gM
    124baYtMrFGt1SJFzqwn7j8Uz1vIiAvBuKPE7Pe+YFHOrljDtb08oa2PdkWAK4dR
    /BAlK1o5GLuT+bB6CAtE7lG/eVzCHeqxtgMUg3nh7aNDiaf7eMMn1GtV006puj4c
    XRrZP89pX7hkiu5Rzwbb9XzwR5lojPXb6ZDLyOFoIjFAazLnnqMKwDjNTBNHIO5Y
    VABhVIEKRBOCXz8pYMNHwhSS8VwC2BSOrVgqtFXtFNBrV3XiGTD7IAbCsEcEQd/D
    sOzshsgJfwXohQqiHc7KrjruUcbyk3oSKl4P5sLmJQ3PNpKg2wPVo/CJcPm2stdp
    Nfjr1Mr3Zk66YCAdDgoxbPSMKO1S/dM5WLy+bdmzfmoOtb+sSgK4O4DJEAON9YFj
    jQDPRfEecbmyVloroG4DY8ibMOPPsBe7VA9vnWONDT8MsYQ/0JM1ma40jyAS7iij
    sVyQKbHuKy0X/cB4A1YHzUITCXyDx18gZgOnpM5gn9LKgWAnilso7qCPfaBXHhzJ
    yE4g0vJijDFL6LOUiKevAgMBAAGjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYD
    VR0PAQH/BAQDAgEGMB0GA1UdDgQWBBTNhrHNHBjiSB9x5+0Rzegs7MRNDzANBgkq
    hkiG9w0BAQsFAAOCAgEAeN0gF7YHcoeNyUMmBUYVKNq/8c0IXn2oXZh4YX4IuQNX
    ZgYP3WWQdlkOO+Y4mw9p83rPTe2sqAGIRut2iCMuDSFoKlEMqf+1jIKrwnhY/bUq
    g5+gfh4Slfek8UPzGdxGTDkt6QURqH1EVEJJsG9hcq0BKSFfvQRtgUlBTdiVzWwo
    RXP4efAijMRG+ZY8810tERrBvAmzXOnOB2WFZORKrhfRfCD2U+T4ZPy8vaVI8yzf
    kzlRseIHmDY2euuiTvhbZOTBiTLUXbnW3NLMIouDaMiq/DKG22FsFDdT/GtwD0LQ
    R6vt3OXBPeb5XyffAlj/0JwLoyvda6Gaiwn0yXQyu1v5X617XvAiwm0MrV3MCW/l
    1N1tFTkSx1q2HcO5SLtbsCLf2qK9w8StIIsnoALPj5VRiyW7xjVsIM3WTH35TRv/
    j79u/JdakFU5n163tLa8P9ql1bJhF4LnC+Gxfrtkcwxf3109iDEGZPeKooRPS2ot
    +1NC/XVvb3ux3q4nXxMJ6iXclhp6XYan4daOibSi22w3UStPsiDT2Ro+5o7IN6P1
    g/D9OQiIoeiOx64Od4C/iJasfY48Jl/yb+54RG208LvBOtwK1TbweyC+9GXZnps/
    EbEOBUNV4V8Uk8eLAeQ73q2EKSzokPH/wWsSMxAZ+BjePHgCNUZAMAdrTCmwJsQ=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: sandbox-ca-trust
  namespace: sandbox-ns-1
