apiVersion: v1
kind: Service
metadata:
  name: sandbox-mitmproxy
  namespace: sandbox-system-ns-1
  labels:
    app.kubernetes.io/name: sandbox-mitmproxy
    app.kubernetes.io/part-of: outbound-api-sandbox
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sandbox-mitmproxy
  ports:
    - name: proxy
      port: 8080
      targetPort: proxy
      protocol: TCP
